# Generated by Django 3.2.4 on 2021-06-28 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='sobrenome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='cpf')),
                ('rg', models.CharField(max_length=8, unique=True, verbose_name='rg')),
                ('telefone', models.CharField(max_length=12, verbose_name='telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('begin_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=500, verbose_name='logradouro')),
                ('bairro', models.CharField(max_length=100, verbose_name='bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='cidade')),
                ('estado', models.CharField(max_length=100, verbose_name='estado')),
                ('numero', models.CharField(blank=True, max_length=100, null=True, verbose_name='numero')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('descricao', models.CharField(blank=True, max_length=50, null=True, verbose_name='descrição do endereço')),
                ('begin_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('endereco_principal', models.BooleanField(default=False, verbose_name='Endereço principal')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_cliente', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'endereco',
            },
        ),
    ]
